local NPCdata = {
    ['Agent Ray' ] = {
        "So you're that hacker we hired for this huh?",
        "I'm Agent Ray, I'm here to give you your tools.",
        "First is the ghost key. sneak behind a guard with this to copy their access codes for the main building",
        "Next is the phack. this will let you hack into thier server room to get the data we need.",
        " just so you know these are government tools, if you misuse them we'll know...",
        "good luck out there",
    },
}

return NPCdata
